export const homeAssets = {
  titleBackground: require('../../assets/home/ui/title-bg.png'),
  loadingImage: require('../../assets/home/ui/loading.png'),
  background: require('../../assets/home/background/home-bg.png'),
  userBar: require('../../assets/home/ui/user-bar.png'),
  pvpBadge: require('../../assets/home/ui/pvp-badge.png'),
  gachaBallIcon: require('../../assets/home/ui/gacha-ball-icon.png'),
  buttons: {
    normalDungeon: require('../../assets/home/buttons/normalDangeon_botton.png'),
    specialDungeon: require('../../assets/home/buttons/specialDangeon_botton.png'),
    deckBuilder: require('../../assets/home/buttons/deckBuilder_botton.png'),
    pieceCatalog: require('../../assets/home/buttons/pieceInfo_botton.png'),
    gacha: require('../../assets/home/buttons/pieceGacha_botton.png'),
    pieceShop: require('../../assets/home/buttons/pieceShop_botton.png'),
  },
  preloadTargets: [
    require('../../assets/home/background/home-bg.png'),
    require('../../assets/home/ui/user-bar.png'),
    require('../../assets/home/ui/pvp-badge.png'),
    require('../../assets/home/ui/gacha-ball-icon.png'),
    require('../../assets/home/buttons/normalDangeon_botton.png'),
    require('../../assets/home/buttons/specialDangeon_botton.png'),
    require('../../assets/home/buttons/deckBuilder_botton.png'),
    require('../../assets/home/buttons/pieceInfo_botton.png'),
    require('../../assets/home/buttons/pieceGacha_botton.png'),
    require('../../assets/home/buttons/pieceShop_botton.png'),
  ],
} as const;
